<template>
  <PostListTemplate :data="data" />
</template>

<script lang="ts" setup>
import { articles } from '~/autogenerated/articles'
import PostListTemplate, { PostListTemplateData } from '~/components/templates/PostListTemplate.vue'

const data: PostListTemplateData = {
  posts: articles
}
</script>

<style>

</style>
