<template>
  <PostListTemplate :data="data" />
</template>

<script lang="ts">
import Vue from 'vue'
import { Component } from 'nuxt-property-decorator'
import { Context } from '@nuxt/types'
import { PostData } from '~/types/Qiita/Api/v2/datas'
import { articles } from '~/autogenerated/articles'
import PostListTemplate, { PostListTemplateData } from '~/components/templates/PostListTemplate.vue'

@Component({
  components: {
    PostListTemplate
  },
  asyncData (_:Context) {
    const posts: PostData[] = articles
    const data: PostListTemplateData = {
      posts
    }
    return {
      data
    }
  }
})
export default class PostPage extends Vue {
  data?: PostListTemplateData
}
</script>

<style>

</style>
