name: GitHub Pages dayly batch

on:
  schedule:
    # 分 時 日 月 曜日 コマンド  UTC時間
    # 毎日日本時間3時に実行
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  # articlesを更新する
  update_articles:
    runs-on: ubuntu-latest # Python3 installed
    name: Update constants/articles.ts and marge
    steps:
      - uses: actions/checkout@v3
      - name: Setup python modules
        run: pip3 install -r requirements.txt
      - name: Generate articles.ts
        run: python3 -B scripts/articles_generator.py constants/articles.ts
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'BOT:Update constants/articles.ts'
  # lintfixを実行する
  lintfix:
    needs: update_articles
    runs-on: ubuntu-latest
    name: Run lintfix
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn lintfix
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'BOT:Fix lintfix'
  deploy:
    needs: lintfix # deployジョブの実行条件

    runs-on: ubuntu-latest
    name: Deploy GithubPages
    steps:
      - uses: actions/checkout@v3
      - name: Restore packages
        run: yarn
      - name: Build
        run: yarn generate:gh-pages
      - name: Deploy (puth dist dir to gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
