name: GitHub Pages cron deploy

on:
  schedule:
    # 分 時 日 月 曜日 コマンド  UTC時間
    # 毎日日本時間3時に実行
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  update_articles:
    runs-on: ubuntu-latest # Python3 installed
    name: Update constants/articles.ts and marge
    steps:
      - uses: actions/checkout@v3
      - name: Setup python modules
        run: pip3 install -r requirements.txt
      - name: Generate articles.ts
        run: python3 -B scripts/articles_generator.py constants/articles.ts
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update constants/articles.ts'
  deploy:
    runs-on: ubuntu-latest
    name: Checkout, build, deploy
    steps:
      - uses: actions/checkout@v3
      - name: aaa
        run: |
          yarn
          sh ./deploy.sh
